/** Normalized transcript snippet used inside the transcript feature. */
export interface TranscriptSnippet {
  text: string;
  start: number;
  duration: number;
}

/** Segment shape returned by youtube-transcript-plus. */
export interface YoutubeTranscriptSegment {
  text: string;
  duration: number;
  offset: number;
  lang: string;
}

/** Caption track metadata returned by youtube-transcript-plus listLanguages. */
export interface YoutubeCaptionTrackInfo {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
}

/** Fetch options passed to youtube-transcript-plus in the transcript client. */
export interface YoutubeTranscriptFetchOptions {
  lang?: string;
  retries?: number;
  retryDelay?: number;
}

/** Raw transcript data returned by the YouTube transcript client. */
export interface FetchedTranscriptData {
  videoId: string;
  snippets: TranscriptSnippet[];
  languageCode: string;
  isGenerated: boolean;
}

/** Result of fetching and concatenating a YouTube video transcript. */
export interface TranscriptFetchResult {
  videoId: string;
  text: string;
  languageCode: string;
  isGenerated: boolean;
  durationSeconds: number;
}
