import { Injectable } from '@nestjs/common';
import { fetchTranscript, listLanguages } from 'youtube-transcript-plus';
import {
  TRANSCRIPT_FETCH_RETRIES,
  TRANSCRIPT_FETCH_RETRY_DELAY_MS,
} from './transcript.constants';
import {
  FetchedTranscriptData,
  YoutubeCaptionTrackInfo,
  YoutubeTranscriptFetchOptions,
  YoutubeTranscriptSegment,
} from './transcript.types';

const DEFAULT_FETCH_CONFIG: YoutubeTranscriptFetchOptions = {
  retries: TRANSCRIPT_FETCH_RETRIES,
  retryDelay: TRANSCRIPT_FETCH_RETRY_DELAY_MS,
};

/** Thin wrapper around `youtube-transcript-plus` for testability. */
@Injectable()
export class YoutubeTranscriptClient {
  /**
   * Fetches transcript snippets for a YouTube video.
   */
  async fetch(
    videoId: string,
    options?: YoutubeTranscriptFetchOptions,
  ): Promise<FetchedTranscriptData> {
    const config: YoutubeTranscriptFetchOptions = {
      ...DEFAULT_FETCH_CONFIG,
      ...options,
    };
    const segments = (await fetchTranscript(
      videoId,
      config,
    )) as YoutubeTranscriptSegment[];
    const languageCode = segments[0]?.lang ?? config.lang ?? 'en';
    const isGenerated = await this.resolveIsGenerated(videoId, languageCode);

    return {
      videoId,
      snippets: segments.map((segment) => ({
        text: segment.text,
        start: segment.offset,
        duration: segment.duration,
      })),
      languageCode,
      isGenerated,
    };
  }

  private async resolveIsGenerated(
    videoId: string,
    languageCode: string,
  ): Promise<boolean> {
    const languages = (await listLanguages(
      videoId,
      DEFAULT_FETCH_CONFIG,
    )) as YoutubeCaptionTrackInfo[];
    const track = languages.find(
      (language) => language.languageCode === languageCode,
    );

    return track?.isAutoGenerated ?? true;
  }
}
