import { ApiProperty } from '@nestjs/swagger';

/** Response returned by the transcript dev fetch endpoint. */
export class TranscriptFetchResponseDto {
  @ApiProperty({
    example: 'dQw4w9WgXcQ',
    description: 'Extracted YouTube video ID',
  })
  videoId!: string;

  @ApiProperty({
    example: 'Never gonna give you up...',
    description: 'Concatenated subtitle text',
  })
  text!: string;

  @ApiProperty({
    example: 'en',
    description: 'BCP 47 language code of the fetched track',
  })
  languageCode!: string;

  @ApiProperty({
    example: true,
    description: 'Whether the subtitles are auto-generated by YouTube',
  })
  isGenerated!: boolean;

  @ApiProperty({
    example: 212,
    description: 'Estimated video duration in seconds from subtitle timestamps',
  })
  durationSeconds!: number;
}
